project_id = "kuidassgxkopjdqziqvq"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.shared-task]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.generate-recurring-entries]
verify_jwt = false

[functions.shared-project]
verify_jwt = false

[functions.shared-shooting]
verify_jwt = false

[functions.shared-meeting]
verify_jwt = false

[functions.sync-socialbu]
verify_jwt = false

[functions.socialbu-post]
verify_jwt = false

[functions.socialbu-accounts]
verify_jwt = false

[functions.socialbu-analytics]
verify_jwt = false

[functions.socialbu-media]
verify_jwt = false

[functions.shared-client-dashboard]
verify_jwt = false
