project_id = "kuidassgxkopjdqziqvq"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.shared-task]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.generate-recurring-entries]
verify_jwt = false
